### PR TITLE
Unmangle backtrace

### PR DESCRIPTION
**Pull request by AngheloAlf**
Change the backtrace when ZAPD crashes into something more readable.

For example, if ZAPD crashes a backtrace like this will be printed:

<details>
<summary>
    Large code block, click to show.
</summary>

```
/lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7f503632a950]
tools/ZAPD/ZAPD.out(_ZN9ZSkeletonC2EPN8tinyxml210XMLElementERKSt6vectorIhSaIhEEiP5ZFile+0x17f) [0x563c2e111f8f]
tools/ZAPD/ZAPD.out(_ZN9ZSkeleton7FromXMLEPN8tinyxml210XMLElementESt6vectorIhSaIhEEiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEP5ZFile+0x5f) [0x563c2e11213f]
tools/ZAPD/ZAPD.out(_ZN5ZFile8ParseXMLE9ZFileModePN8tinyxml210XMLElementENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x2817) [0x563c2e101627]
tools/ZAPD/ZAPD.out(_ZN5ZFileC1E9ZFileModePN8tinyxml210XMLElementENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_b+0x2aa) [0x563c2e1021ba]
tools/ZAPD/ZAPD.out(_Z5ParseRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_9ZFileMode+0x1c7) [0x563c2e0dc8c7]
tools/ZAPD/ZAPD.out(_Z7NewMainiPPc+0x34c) [0x563c2e0dd0dc]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7f5036311cb2]
tools/ZAPD/ZAPD.out(_start+0x2e) [0x563c2e0d755e]
tools/ZAPD/ZAPD.out(_Z12ErrorHandleri+0x50)[0x563c2e0dab70]
/lib/x86_64-linux-gnu/libc.so.6(+0x41950)[0x7f503632a950]
tools/ZAPD/ZAPD.out(_ZN9ZSkeletonC2EPN8tinyxml210XMLElementERKSt6vectorIhSaIhEEiP5ZFile+0x17f)[0x563c2e111f8f]
tools/ZAPD/ZAPD.out(_ZN9ZSkeleton7FromXMLEPN8tinyxml210XMLElementESt6vectorIhSaIhEEiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEP5ZFile+0x5f)[0x563c2e11213f]
tools/ZAPD/ZAPD.out(_ZN5ZFile8ParseXMLE9ZFileModePN8tinyxml210XMLElementENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x2817)[0x563c2e101627]
tools/ZAPD/ZAPD.out(_ZN5ZFileC1E9ZFileModePN8tinyxml210XMLElementENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_b+0x2aa)[0x563c2e1021ba]
tools/ZAPD/ZAPD.out(_Z5ParseRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_9ZFileMode+0x1c7)[0x563c2e0dc8c7]
tools/ZAPD/ZAPD.out(_Z7NewMainiPPc+0x34c)[0x563c2e0dd0dc]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2)[0x7f5036311cb2]
tools/ZAPD/ZAPD.out(_start+0x2e)[0x563c2e0d755e]
```

</details>

With this change, the crash backtrace would look like:

<details>
<summary>
    Large code block, click to show.
</summary>

```
1   /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7f7d86241950]
2   ZSkeleton::ZSkeleton(tinyxml2::XMLElement*, std::vector<unsigned char, std::allocator<unsigned char> > const&, int, ZFile*) (+0x17F)
3   ZSkeleton::FromXML(tinyxml2::XMLElement*, std::vector<unsigned char, std::allocator<unsigned char> >, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ZFile*) (+0x5F)
4   ZFile::ParseXML(ZFileMode, tinyxml2::XMLElement*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (+0x2896)
5   ZFile::ZFile(ZFileMode, tinyxml2::XMLElement*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) (+0x2AA)
6   Parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ZFileMode) (+0x1A1)
7   NewMain(int, char**) (+0x350)
8   __libc_start_main (+0xF2)
9   _start (+0x2E)
```

</details>

I don't know how portable this change is. We would need to test it in Mac, ARM, WSL, etc. 
Tested architectures:
- [X] Linux x86-64
- [X] Linux ARM aarch64 (thanks @louist103)
- [ ] Mac
- [ ] Mac ARM (?)
- [ ] WSL
- [ ] ~Mips3~

This change would also fix the problem of `make` doing a full compile of ZAPD each the command is run.
Lastly, I changed the remaining `throw`s that threw an string instead of an exception. Also changes the warnings to be printed to `stderr` instead of normal `stdout` for consistency sake.

### CODE REVIEW

**Review by louist103 — APPROVED** [review]
Works as intended on aarch64.

**Review by NEstelami — APPROVED** [review]
Do we want to wait on testing this with all platforms before merging in?

**Comment by AngheloAlf** [comment]
I son't think any problem could happen with either WSL nor Mac.
Mac ARM may be a problem, but we could try to fix it (or rollback in the worst case) of anybody suffers any problem with this.
So, yeah lets merge it.

**Comment by NEstelami** [comment]
Roger that.

**Pull request merged**
