### PR TITLE
Fix some memory leaks issues

### PR DESCRIPTION
**Pull request by AngheloAlf**
I mainly changed a lot of raw pointers into `shared_ptr`, so that object deallocates itself when it is no longer used. I tried finding the places where the memory was leaking and adding `delete`s, but they were too much places and also it somehow randomly crashed during my testing, so I just went with the `shared_ptr` solution.

There were also a lot of places where a heap allocation (`new`) was used when it wasn't necessary, and for some reason the object wasn't being `delete`d, so it just leaked...

I would suggest to avoid using pointers unless it is really neaded (like storing a bunch of objects of different types using inheritance). And even in that case, try to use smart pointers so you don't have to worry about deallocating that memory.

This should fix almost all the problems listed in #52 (except the last one).

And for some numbers, this should fix around 50% of leaked memory. 
To get this number, I measured the leaked memory when running `extract_assets.py` with and without this change. It went down from `1254.07 MiB` leaked to `619.66 MiB` leaked.

There are still things to fix in `HighLevel` and `ZRoom` folders. I tried to fix stuff there, but it exploded in my face... Maybe I'll try to fix them later.

### CODE REVIEW

**Comment by NEstelami** [comment]
Don't worry about the stuff in the `HighLevel` folder. It's all experimental and doesn't really apply to the extraction process.

**Comment by AngheloAlf** [comment]
> 
> 
> Don't worry about the stuff in the `HighLevel` folder. It's all experimental and doesn't really apply to the extraction process.

The changes I made in `HighLevel` are minimal. I made them because ZAPD will not compile otherwise.

**Comment by fig02** [comment]
theres a handful of conflicts to resolve in here, unsure if we want to do this before or after clang-format. up to you alf

**Comment by AngheloAlf** [comment]
I think I'll start over with this. There are many new changes, and now that I now a lot more of ZAPD I think I could do a better job starting over.

**Pull request closed without merging**
