### PR TITLE
Defines for texture dimensions

### PR DESCRIPTION
**Pull request by EllipticEllipsis**
Tell ZAPD to automatically create defines in the header for a texture's width, height, and size (in bytes), if it is provided the attribute `Defines` in the file header. I did not specify a particular value it should have, but `true` or similar is probably the way to go.

<details>
<summary>
Example 1
</summary>

```c
extern u64 gTitleScreenZeldaLogoTex[];
#define TITLE_SCREEN_ZELDA_LOGO_TEX_WIDTH 144
#define TITLE_SCREEN_ZELDA_LOGO_TEX_HEIGHT 64
#define TITLE_SCREEN_ZELDA_LOGO_TEX_SIZE 0x9000

extern u64 gTitleScreenMajorasMaskSubtitleTex[];
#define TITLE_SCREEN_MAJORAS_MASK_SUBTITLE_TEX_WIDTH 104
#define TITLE_SCREEN_MAJORAS_MASK_SUBTITLE_TEX_HEIGHT 16
#define TITLE_SCREEN_MAJORAS_MASK_SUBTITLE_TEX_SIZE 0x680

extern u64 gTitleScreenMajorasMaskSubtitleMaskTex[];
#define TITLE_SCREEN_MAJORAS_MASK_SUBTITLE_MASK_TEX_WIDTH 104
#define TITLE_SCREEN_MAJORAS_MASK_SUBTITLE_MASK_TEX_HEIGHT 16
#define TITLE_SCREEN_MAJORAS_MASK_SUBTITLE_MASK_TEX_SIZE 0x680

extern u64 gTitleScreenTheLegendOfTextTex[];
#define TITLE_SCREEN_THE_LEGEND_OF_TEXT_TEX_WIDTH 72
#define TITLE_SCREEN_THE_LEGEND_OF_TEXT_TEX_HEIGHT 8
#define TITLE_SCREEN_THE_LEGEND_OF_TEXT_TEX_SIZE 0x240

extern u64 gTitleScreenDisplayEffectMask00Tex[];
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK00_TEX_WIDTH 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK00_TEX_HEIGHT 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK00_TEX_SIZE 0x800

extern u64 gTitleScreenDisplayEffectMask01Tex[];
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK01_TEX_WIDTH 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK01_TEX_HEIGHT 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK01_TEX_SIZE 0x800

extern u64 gTitleScreenDisplayEffectMask10Tex[];
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK10_TEX_WIDTH 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK10_TEX_HEIGHT 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK10_TEX_SIZE 0x800

extern u64 gTitleScreenDisplayEffectMask11Tex[];
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK11_TEX_WIDTH 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK11_TEX_HEIGHT 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK11_TEX_SIZE 0x800

extern u64 gTitleScreenDisplayEffectMask02Tex[];
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK02_TEX_WIDTH 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK02_TEX_HEIGHT 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK02_TEX_SIZE 0x800

extern u64 gTitleScreenDisplayEffectMask12Tex[];
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK12_TEX_WIDTH 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK12_TEX_HEIGHT 64
#define TITLE_SCREEN_DISPLAY_EFFECT_MASK12_TEX_SIZE 0x800

extern u64 gTitleScreenAppearEffectMask00Tex[];
#define TITLE_SCREEN_APPEAR_EFFECT_MASK00_TEX_WIDTH 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK00_TEX_HEIGHT 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK00_TEX_SIZE 0x800

extern u64 gTitleScreenAppearEffectMask01Tex[];
#define TITLE_SCREEN_APPEAR_EFFECT_MASK01_TEX_WIDTH 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK01_TEX_HEIGHT 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK01_TEX_SIZE 0x800

extern u64 gTitleScreenAppearEffectMask10Tex[];
#define TITLE_SCREEN_APPEAR_EFFECT_MASK10_TEX_WIDTH 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK10_TEX_HEIGHT 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK10_TEX_SIZE 0x800

extern u64 gTitleScreenAppearEffectMask11Tex[];
#define TITLE_SCREEN_APPEAR_EFFECT_MASK11_TEX_WIDTH 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK11_TEX_HEIGHT 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK11_TEX_SIZE 0x800

extern u64 gTitleScreenAppearEffectMask02Tex[];
#define TITLE_SCREEN_APPEAR_EFFECT_MASK02_TEX_WIDTH 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK02_TEX_HEIGHT 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK02_TEX_SIZE 0x800

extern u64 gTitleScreenAppearEffectMask12Tex[];
#define TITLE_SCREEN_APPEAR_EFFECT_MASK12_TEX_WIDTH 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK12_TEX_HEIGHT 64
#define TITLE_SCREEN_APPEAR_EFFECT_MASK12_TEX_SIZE 0x800

extern u64 gTitleScreenFlame0Tex[];
#define TITLE_SCREEN_FLAME0_TEX_WIDTH 32
#define TITLE_SCREEN_FLAME0_TEX_HEIGHT 32
#define TITLE_SCREEN_FLAME0_TEX_SIZE 0x400

extern u64 gTitleScreenFlame1Tex[];
#define TITLE_SCREEN_FLAME1_TEX_WIDTH 32
#define TITLE_SCREEN_FLAME1_TEX_HEIGHT 32
#define TITLE_SCREEN_FLAME1_TEX_SIZE 0x400

extern u64 gTitleScreenFlame2Tex[];
#define TITLE_SCREEN_FLAME2_TEX_WIDTH 32
#define TITLE_SCREEN_FLAME2_TEX_HEIGHT 32
#define TITLE_SCREEN_FLAME2_TEX_SIZE 0x400

extern u64 gTitleScreenFlame3Tex[];
#define TITLE_SCREEN_FLAME3_TEX_WIDTH 32
#define TITLE_SCREEN_FLAME3_TEX_HEIGHT 32
#define TITLE_SCREEN_FLAME3_TEX_SIZE 0x400

extern u64 gTitleScreenCopyright2000NintendoTex[];
#define TITLE_SCREEN_COPYRIGHT2000_NINTENDO_TEX_WIDTH 128
#define TITLE_SCREEN_COPYRIGHT2000_NINTENDO_TEX_HEIGHT 16
#define TITLE_SCREEN_COPYRIGHT2000_NINTENDO_TEX_SIZE 0x800

extern u64 gTitleScreenControllerNotConnectedTextTex[];
#define TITLE_SCREEN_CONTROLLER_NOT_CONNECTED_TEXT_TEX_WIDTH 256
#define TITLE_SCREEN_CONTROLLER_NOT_CONNECTED_TEXT_TEX_HEIGHT 9
#define TITLE_SCREEN_CONTROLLER_NOT_CONNECTED_TEXT_TEX_SIZE 0x480

extern u64 gTitleScreenInsertControllerTextTex[];
#define TITLE_SCREEN_INSERT_CONTROLLER_TEXT_TEX_WIDTH 144
#define TITLE_SCREEN_INSERT_CONTROLLER_TEXT_TEX_HEIGHT 9
#define TITLE_SCREEN_INSERT_CONTROLLER_TEXT_TEX_SIZE 0x288

extern u64 gTitleScreenMajorasMaskTex[];
#define TITLE_SCREEN_MAJORAS_MASK_TEX_WIDTH 128
#define TITLE_SCREEN_MAJORAS_MASK_TEX_HEIGHT 112
#define TITLE_SCREEN_MAJORAS_MASK_TEX_SIZE 0xE000


```

</details>

<details>
<summary>
Example 2
</summary>

```c
extern s16 object_firefly_Anim_00017CFrameData[];
extern JointIndex object_firefly_Anim_00017CJointIndices[];
extern AnimationHeader object_firefly_Anim_00017C;
extern u8 object_firefly_possiblePadding_00018C[];

extern u64 object_firefly_Tex_000190[];
#define OBJECT_FIREFLY__TEX_000190_WIDTH 8
#define OBJECT_FIREFLY__TEX_000190_HEIGHT 8
#define OBJECT_FIREFLY__TEX_000190_SIZE 0x80

extern u64 object_firefly_Tex_000210[];
#define OBJECT_FIREFLY__TEX_000210_WIDTH 8
#define OBJECT_FIREFLY__TEX_000210_HEIGHT 8
#define OBJECT_FIREFLY__TEX_000210_SIZE 0x80

extern u64 object_firefly_Tex_000290[];
#define OBJECT_FIREFLY__TEX_000290_WIDTH 8
#define OBJECT_FIREFLY__TEX_000290_HEIGHT 8
#define OBJECT_FIREFLY__TEX_000290_SIZE 0x80

extern u64 object_firefly_Tex_000310[];
#define OBJECT_FIREFLY__TEX_000310_WIDTH 16
#define OBJECT_FIREFLY__TEX_000310_HEIGHT 8
#define OBJECT_FIREFLY__TEX_000310_SIZE 0x100

extern u64 object_firefly_Tex_000410[];
#define OBJECT_FIREFLY__TEX_000410_WIDTH 8
#define OBJECT_FIREFLY__TEX_000410_HEIGHT 16
#define OBJECT_FIREFLY__TEX_000410_SIZE 0x100

extern u64 object_firefly_Tex_000510[];
#define OBJECT_FIREFLY__TEX_000510_WIDTH 4
#define OBJECT_FIREFLY__TEX_000510_HEIGHT 16
#define OBJECT_FIREFLY__TEX_000510_SIZE 0x80

extern u64 object_firefly_Tex_000590[];
#define OBJECT_FIREFLY__TEX_000590_WIDTH 8
#define OBJECT_FIREFLY__TEX_000590_HEIGHT 8
#define OBJECT_FIREFLY__TEX_000590_SIZE 0x80

extern u64 object_firefly_Tex_000610[];
#define OBJECT_FIREFLY__TEX_000610_WIDTH 8
#define OBJECT_FIREFLY__TEX_000610_HEIGHT 16
#define OBJECT_FIREFLY__TEX_000610_SIZE 0x100

extern u64 object_firefly_Tex_000710[];
#define OBJECT_FIREFLY__TEX_000710_WIDTH 4
#define OBJECT_FIREFLY__TEX_000710_HEIGHT 16
#define OBJECT_FIREFLY__TEX_000710_SIZE 0x80

extern u64 object_firefly_Tex_000790[];
#define OBJECT_FIREFLY__TEX_000790_WIDTH 16
#define OBJECT_FIREFLY__TEX_000790_HEIGHT 8
#define OBJECT_FIREFLY__TEX_000790_SIZE 0x100

extern Vtx object_fireflyVtx_000890[];
extern Gfx object_firefly_DL_000D30[];
extern Gfx object_firefly_DL_000F40[];
extern Gfx object_firefly_DL_001038[];
extern Gfx object_firefly_DL_001100[];
extern Gfx object_firefly_DL_0011C8[];
extern Gfx object_firefly_DL_001290[];
extern Gfx object_firefly_DL_001358[];
extern Gfx object_firefly_DL_001420[];
extern Gfx object_firefly_DL_0014E8[];
extern Gfx object_firefly_DL_0015B0[];
extern Gfx object_firefly_DL_001678[];
extern StandardLimb object_firefly_Standardlimb_001708;
extern StandardLimb object_firefly_Standardlimb_001714;
extern StandardLimb object_firefly_Standardlimb_001720;
extern StandardLimb object_firefly_Standardlimb_00172C;
extern StandardLimb object_firefly_Standardlimb_001738;
extern StandardLimb object_firefly_Standardlimb_001744;
extern StandardLimb object_firefly_Standardlimb_001750;
extern StandardLimb object_firefly_Standardlimb_00175C;
extern StandardLimb object_firefly_Standardlimb_001768;
extern StandardLimb object_firefly_Standardlimb_001774;
extern StandardLimb object_firefly_Standardlimb_001780;
extern StandardLimb object_firefly_Standardlimb_00178C;
extern StandardLimb object_firefly_Standardlimb_001798;
extern StandardLimb object_firefly_Standardlimb_0017A4;
extern StandardLimb object_firefly_Standardlimb_0017B0;
extern StandardLimb object_firefly_Standardlimb_0017BC;
extern StandardLimb object_firefly_Standardlimb_0017C8;
extern StandardLimb object_firefly_Standardlimb_0017D4;
extern StandardLimb object_firefly_Standardlimb_0017E0;
extern StandardLimb object_firefly_Standardlimb_0017EC;
extern StandardLimb object_firefly_Standardlimb_0017F8;
extern StandardLimb object_firefly_Standardlimb_001804;
extern StandardLimb object_firefly_Standardlimb_001810;
extern StandardLimb object_firefly_Standardlimb_00181C;
extern StandardLimb object_firefly_Standardlimb_001828;
extern StandardLimb object_firefly_Standardlimb_001834;
extern StandardLimb object_firefly_Standardlimb_001840;
extern void* object_firefly_Skel_0018B8Limbs[];
extern SkeletonHeader object_firefly_Skel_0018B8;


```

</details>

The hard part was the formatting. I introduced a new function to convert strings from camelCase to SCREAMING_SNAKE_CASE, which works well for custom names, less so for the automatically generated ones. The logic for how to print the newlines was also surprisingly complex, and wasn't helped by C++ being C++ while I was trying to get it to work.

This partly addresses #212 : the second half, using the defines automatically in displaylists, cannot be done without changes to libgfxd to allow for more flexible interpretation: currently, it can only read the raw numbers out of the binary data.

### CODE REVIEW

**Comment by mdtauk** [comment]
Why just width and height, and not also position?

**Comment by EllipticEllipsis** [comment]
I'm sorry, what do you mean by position?

**Comment by mdtauk** [comment]
> I'm sorry, what do you mean by position?

I believe some of the title-screen elements are positioned in 2D space, so x and y coordinates from the top left of the screen space?  Although, thinking on it some more - I guess that is more appropriate in the OoT and MM repos, rather than for ZAPD, so please disregard 😊

**Comment by EllipticEllipsis** [comment]
Yes, those are not present in the asset files, and indeed, the position coordinates are not always the position of the same part, and would not cover everything anyway. Already done for object_mag in MM: https://github.com/zeldaret/mm/blob/master/src/overlays/actors/ovl_En_Mag/z_en_mag.c#L626-L672

**Review by NEstelami — APPROVED** [review]
Looks solid. I'm planning to make some static functions with descriptive names for creating declarations, since having so many constructors with different combinations of arguments can be confusing. Great work on this.

**Pull request merged**
