### PR TITLE
ZRoom refactor

### PR DESCRIPTION
**Pull request by AngheloAlf**
- Clean up a lot of ZRoom/Commands code.
- Export the rooms/scenes commands as an array of `SCmdBase`. The output for those arrays use the macros made by @Zelllll 
- General cleanup of rooms/scenes outputted code.
- ~~Automatically adjust TLUTs to be smaller in case of intersections.~~
- Remove a lot of unnecessary pointers and destructors.
- Properly implement `ZPath`.
- Move the class `Declaration` to its own file.
- Probably something else I don't remember right now.

Because of macros being needed for rooms commands, this will not build properly by Jenkins. I'll do a PR to add the new macros to the OoT repo soon :tm:

Examples:

Current command output:
```c
static SCmdSoundSettings bowling_sceneSet0000Cmd00 = {  0x15, 0x05, 0x00, 0x00, 0x00, 0x00, 0x13, 0x4E }; // 0x0000

static SCmdRoomList bowling_sceneSet0000Cmd01 = {  0x04, 0x01, (u32)&bowling_sceneRoomList0x000080 }; // 0x0008

static SCmdTransiActorList bowling_sceneSet0000Cmd02 = {  0x0E, 0x01, (u32)bowling_sceneTransitionActorList0x000070 }; // 0x0010

static SCmdMiscSettings bowling_sceneSet0000Cmd03 = {  0x19, 0x00, 0x0000000E }; // 0x0018

static SCmdColHeader bowling_sceneSet0000Cmd04 = {  0x03, 0x00, (u32)&bowling_sceneCollisionHeader0x001A74 }; // 0x0020

static SCmdEntranceList bowling_sceneSet0000Cmd05 = {  0x06, 0x00, (u32)&bowling_sceneEntranceList0x000088 }; // 0x0028

static SCmdSpecialFiles bowling_sceneSet0000Cmd06 = {  0x07, 0x00, 0x0002 }; // 0x0030

static SCmdSpawnList bowling_sceneSet0000Cmd07 = {  0x00, 0x01, (u32)&bowling_sceneStartPositionList0x000060 }; // 0x0038

static SCmdSkyboxSettings bowling_sceneSet0000Cmd08 = {  0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01 }; // 0x0040

static SCmdExitList bowling_sceneSet0000Cmd09 = {  0x13, 0x00, (u32)&bowling_sceneExitList0x00008C }; // 0x0048

static SCmdLightSettingList bowling_sceneSet0000Cmd0A = {  0x0F, 4, (u32)&bowling_sceneLightSettings0x000090 }; // 0x0050

static SCmdEndMarker bowling_sceneSet0000Cmd0B = {  0x14, 0x00, 0x00 }; // 0x0058

```

New command output:
```c
static SCmdBase bowling_sceneSet0000[12] = {
	SCENE_CMD_SOUND_SETTINGS(5, 19, 78),
	SCENE_CMD_ROOM_LIST(1, bowling_sceneRoomList0x000080),
	SCENE_CMD_TRANSITION_ACTOR_LIST(1, bowling_sceneTransitionActorList_000070),
	SCENE_CMD_MISC_SETTINGS(0x00, 0x0000000E),
	SCENE_CMD_COL_HEADER(&bowling_sceneCollisionHeader_001A74),
	SCENE_CMD_ENTRANCE_LIST(bowling_sceneEntranceList0x000088),
	SCENE_CMD_SPECIAL_FILES(0x00, 0x0002),
	SCENE_CMD_SPAWN_LIST(1, bowling_sceneStartPositionList0x000060),
	SCENE_CMD_SKYBOX_SETTINGS(0x00, 0, 0, 1),
	SCENE_CMD_EXIT_LIST(bowling_sceneExitList_00008C),
	SCENE_CMD_ENV_LIGHT_SETTINGS(4, bowling_sceneLightSettings0x000090),
	SCENE_CMD_END(),
}; 
```

### CODE REVIEW

**Comment by AngheloAlf** [comment]
Converting this PR to a draft until we sort out the OoT and MM scenes/rooms changes

**Comment by Zelllll** [comment]
Alright so what is left with this?

**Comment by AngheloAlf** [comment]
I think we are waiting for https://github.com/zeldaret/oot/pull/792 to get merged.

**Comment by AngheloAlf** [comment]
The OoT repo merged the new scene macros, so this now can be merged.

**Pull request merged**
